auth:
  build: .
  ports:
    - "8102:8000"
  environment:
    - DEBUG
    - PREFERRED_URL_SCHEME
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_SECRET
    - JWT_LIFETIME
  command: /bin/sh /app/docker-entrypoint.sh
