database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5405:5432"
  environment:
    POSTGRES_DB: auths
    POSTGRES_USER: auths
    POSTGRES_PASSWORD: insecure


web:
  build: ./web
  ports:
    - "8102:8000"
  links:
    - database:database
  environment:
    SECRET_KEY: hoi
    DB_NAME: auths
    DB_USER: auths
    DB_PASSWORD: insecure
