auth:
  build: .
  ports:
    - "8109:8000"
  environment:
    - DEBUG
    - AUTH_SKIP_CONF_CHECK
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_SHARED_SECRET_KEY
    - JWT_LIFETIME
  command: make -C /app run

database:
  image: postgres:9.5
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=authz
    - POSTGRES_USER=authuser
    - POSTGRES_PASSWORD=authpassword
