database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  ports:
    - "5405:5432"
  environment:
    POSTGRES_DB: authenticatie
    POSTGRES_USER: authenticatie
    POSTGRES_PASSWORD: insecure


web:
  build: ./web
  ports:
    - "8102:8000"
  links:
    - database:database
  environment:
    SECRET_KEY: hoi
    DB_NAME: authenticatie
    DB_USER: authenticatie
    DB_PASSWORD: insecure
  volumes:
    - ./reports:/app/reports
