auth:
  build: .
  ports:
    - "8109:8000"
  links:
    - database
  environment:
    - LOGLEVEL=DEBUG
    - SIAM_URL
    - SIAM_A_SELECT_SERVER
    - SIAM_APP_ID
    - SIAM_SHARED_SECRET
    - JWT_REFRESH_SECRET
    - JWT_ACCESS_SECRET
    - PG_HOST=database
    - PG_PORT=5432
    - PG_USER=authuser
    - PG_PASS=authpassword
    - PG_DB=authz
  command: make -C /app run

database:
  image: postgres:9.5
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_DB=authz
    - POSTGRES_USER=authuser
    - POSTGRES_PASSWORD=authpassword
