database:
  image: admin.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: auths


tests:
  build: ../web
  links:
    - database:database
  volumes:
    - ../reports:/app/reports
  environment:
    DATABASE_NAME: auths
    DATABASE_USER: auths
    DATABASE_PASSWORD: insecure
  command: bash -c "/app/docker-wait.sh && python manage.py jenkins"


web:
  build: ../web
  links:
    - database:database
  environment:
    DB_NAME: auths
    DB_USER: auths
    DB_PASSWORD: insecure
